### ISSUE TITLE
Create new Multi-Signature interface

### ISSUE THREAD

**Issue by Kersten-TCD** [telosnetwork/open-block-explorer#157]
The Open Block Explorer requires an easy to use Multi-Signature interface that allows creation, visualization and signing of MSIGs. These features are required specifically required for Block Producers (BPs) and "pro" users as of today. Within the scope of the implementation "novice" users will also be targeted to open this powerful toolset to a broader part of the community.

Detroit Ledget Technologies (DLT) has been requested to work on this component by Telos Core Development (TCD). The scoping document is attached in this issue for further evaluation. Once consensus is reached on the components and design, separate issues will be created to start active work.

### Current Problem
Members of the Telos Network do not currently have an easy-to-use interface to generate and sign msigs. Creation heavily relies upon cleos command line knowledge and signing can be done through the EOS Authority explorer but is missing key information about the proposals themselves on the front-end.

### Project Goals
The goal of this project is to create a msig creation tool that is focused on power users such as block producers and application developers. The second phase of the project will shift focus to developing an msig tool that can be used by novice users for everyday actions and a library of msig templates.

### Initial Project Scope & Timeline

The following timeline represents a worst case scenario in terms of number of hours. Sprints represent 30 hours per week for 2 weeks. The rate remains constant regardless of the number of DLT team members contributing to the project.
Some initial mockups were created in Figma and exports of those views can be found at the bottom of this document.

### Phase 1

**Pre-development Sprint 1 (in-progress)**
- Design
- Meeting with Rami in the middle of the sprint
- Elton getting familiar with current code
- Notification investigation

**Development Sprint 1**
- Building a msig transaction
- Notification research/dev
 
**Development Sprint 2**
- Signing a msig transaction
- Getting notified that a transaction needs to be signed

**Development Sprint 3**
- Notifying the proposer of the action that all signatures have been acquired
- Execute action
- Bug fixing

### Phase 2
This phase will focus on creating an interface that is stripped down and more usable for novice users.

Draft Designs:

**Proposal List**
![proposal list](https://user-images.githubusercontent.com/39388424/165900707-818ce94e-7bc7-453f-96b1-99cdfcc6cb5b.png)

**New Proposal**
![New Proposal](https://user-images.githubusercontent.com/39388424/165900840-ffa65aec-e5ad-4b40-8fb9-9dbb6f1ab78e.png)

**Proposal Created Successfully** 
![Proposal created](https://user-images.githubusercontent.com/39388424/165900888-4cadc4c4-652d-40b2-860a-82580715a70a.png)

**Single Proposal View**
![Single Proposal View](https://user-images.githubusercontent.com/39388424/165900917-d631bad0-e931-4ef8-94a0-b6400e500581.png)

[Telos OBE Msig Tool Part 1 Proposal - For Github.pdf](https://github.com/telosnetwork/open-block-explorer/files/8588739/Telos.OBE.Msig.Tool.Part.1.Proposal.-.For.Github.pdf)

**Comment by Kersten-TCD** [comment]
Comments @poplexity raised on Telegram 04.28.2022:

1. On the part where you add the permissions you want on the signature, I think it would be better to have a dropdown where you can pick from:

- BPs (it's magic permission eosio.prods, I have the javascript to share that pulls the list of BPs and generates the permissions for this)
- From a permission (You could then pick tf@active and it would add all the signers on the tf@active account)
- Specify permissions

2. On the view of the propsed transactions... if it is setcode or setabi we should not show the raw data, but show the sha256 hash for the code being deployed and for the decoded JSON for the abi

**Comment by karynemayer** [comment]
Pre-development Sprint 1
- [x]  Design
- [ ] Meeting with Rami in the middle of the sprint
- [ ] Notifications research

Development Sprint 1
- [ ] Listing msig transactions filtered by proposer, BP proposals and listing all of them
- [ ] Building a msig transaction

Development Sprint 2
- [ ] Signing a msig transaction
- [ ] Getting notified that a transaction needs to be signed

Development Sprint 3
- [ ] Execute action
- [ ] Notifying the proposer of the action that all signatures have been acquired

Bug fixing
- [ ]  TBD

**Comment by Kersten-TCD** [comment]
@ramijames @karynemayer to coordinate meeting for Thursday to discuss and fine tune designs.

**Comment by karynemayer** [comment]
I'm closing this issue because we already delivered the MVP version. Any further changes will be described in new issues.
