### ISSUE TITLE
MSIG example csv file

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/open-block-explorer#356]
## Overview

There is still some confusion on how to fill out the example CSV file, such as the precision of the transfer amount. Also, the way its creating the actions could be improved.
## Acceptance criteria

- Provide an example of how the csv must be filled
- When uploading, the `Actor` from requested approvals should be the account in `from`
- 
## Tasks

- [ ] Add a filled row to the `example.csv` file
- [ ] Identify the `Actor` from requested approvals
- [ ] Add the `Actor` as the `from` account when parsing the csv file
