### ISSUE TITLE
Pagination not working on account pages

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/open-block-explorer#546]
## Overview
The information is only sometimes shown or updated when navigating through the transactions pages within an account. The image below shows an example of `undefined` instead of the amount of TLOS transferred. Also, the dropdown under the transfer action doesn't do anything. 

<img width="1638" alt="Screenshot 2023-01-23 at 15 34 50" src="https://user-images.githubusercontent.com/2939354/214176506-9076626c-bef2-4e41-acc4-3b454c357ddc.png">

## Steps to reproduce
1. In OBE, search for the `tf` account
2. Scroll down to transactions
3. Keep 10 transactions per page to facilitate your testing
4. Click Prev and Next several times, until you see the error described above

## Acceptance criteria
* No transaction data can be `undefined`
* Dropdown sign should only be applied to expandable transactions
* Indicate when the transaction doesn't have a memo with `no memo`. Apply italics and transparency in the text to indicate it as a placeholder.
* When navigating through the pages, the results should be consistently updated.
* When going back to a previous page, the results seen before should be in the same place.
* Transaction dates should look consistent

## Tasks
- [x] Identify the root cause of the pagination
- [x] Identify the root cause of undefined for transfers (if reproducible)
- [x] Discuss solutions with the team
- [x] Implement the solution

**Comment by Viterbo** [comment]
There are several problems found in the current implementation:
- The cause for the undefined data for transactions was because that data is calculated only once on the Component's setup but is never updated. The problem is that when the user changes the page, all components are reused and the internal data is never updated.
- The switcher to see more data is calculated again, only once in the setup function which is never called again, but the internal data changes as the user change the page. So, the calculation for the need for that switcher gets outdated from the second page and on.
- The problem with the pagination seems to be outside the website. It happens that different calls for the same history page for a quiet account return a group of ten actions but with a different offset.


Solutions
- change all calculated variables to actual computed-type variables.
- Maintain an internal buffer for transaction history and keep it for searches locally.

**Comment by Viterbo** [comment]
## Scrennshots

- In the first couple of screenshots you can see the undefined being captured and debugged (on the right). The problem was in the variable `transferData` which was calculated only once on the setup function and now is a computed (always updated) variable. You can see in the second screenshot that the problem was solved.

![undefined-err](https://user-images.githubusercontent.com/4420760/216835978-1ab80aeb-3cbd-462e-bb27-69dbd9f813a2.png)
![undefined-ok](https://user-images.githubusercontent.com/4420760/216835979-6af9d85f-7ed0-4209-82f6-c9b483d32bd2.png)

- In this case, I have captured two different responses for the same paginated query. You can see that both includes the same transaction but with different offset.
![query-1](https://user-images.githubusercontent.com/4420760/216835974-0b64ac5b-3b82-46b5-98e4-ddec1335f774.png)
![query-2](https://user-images.githubusercontent.com/4420760/216835975-7bd3e04b-f030-4c7c-9d1b-9bb8daaeca09.png)

**Comment by Viterbo** [comment]
we discussed with @donnyquixotic to decide what to do with the filters in the transaction pagination and I wrote down a [comment on the issue](https://github.com/telosnetwork/open-block-explorer/issues/547#issuecomment-1419603144) for that problem.
