### ISSUE TITLE
Preferred network being set in landing page

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/open-block-explorer#746]
## Overview

With the inclusion of other networks to OBE, we want to allow the users to select their preferred network. The preferred network is the network to which OBE will default to whenever its accessed by its empty URL, i.e. without the network parameter. This configuration should be set in `localStorage`.

Whenever the configuration is not defined in the browser's `localStorage` **and** the URL doesn't contain the network, the user should be presented with a simple landing page that contains the list of all available networks. The user will be redirected to the selected network, and, this will be their preferred network.

At this point, the only way to change the user's preferred network within a browser will be for them to manually clean their `localStorage`. In the future, a local preferences feature should be worked on.

## Acceptance criteria
- localStorage should have the ability to store the preferred browser
- if preferred network is not set and OBE URL doesn't include network, user should be directed to the landing page
- if preferred network is set and OBE URL doesn't include network, redirect to preferred network main page
- preferred network should be set when network is selected in the landing page

## Tasks
- [ ] Design the simplest possible landing page 
- [ ] Include configuration to `localStorage`
- [ ] Set configuration by accessing landing page
