### ISSUE TITLE
Update Telos Branding

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#808]
**Description**
Update theme using new logos & colors for Telos (mainnet & testnet config)

**Tasks**

- [ ] Acorn and Telos Logos (responsive) - header 
- [ ] Acorn logo - favicon
- [ ] Update colors/theme

**Blockers**

- [ ] App theme colors

**Resources**
![telos-circle-logo](https://github.com/telosnetwork/telos-wallet/assets/6848910/f70e075a-528b-4206-bbde-5c8daea7b1ec)
![telos-logo](https://github.com/telosnetwork/telos-wallet/assets/6848910/2f169404-4a33-42dc-b0ac-fcd4e062a5dd)
![telos-logo-dark](https://github.com/telosnetwork/telos-wallet/assets/6848910/f1da63f1-68fe-4623-b49a-42b5f9d5f2c6)
